name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y libeigen3-dev
          sudo apt install -y libfftw3-dev
          sudo apt install -y libgtest-dev
          sudo apt install -y libbenchmark-dev
          sudo rm -rf /var/lib/apt/lists/*
      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Benchmark
        run: cmake --build build --target benchmark
      - name: Python
        working-directory: ./python
        run: |
          sudo apt -y install python3
          sudo apt -y install python3-pip
          python3 -m pip install --upgrade pip setuptools wheel
          cmake -S . -B build
          cmake --build build
          cmake --install build
          python3 -m pip install .[test]
          python3 -m pytest --verbose
